/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

public class App {
    public static void main(String[] args) {
        LogOutput logOutput = new LogOutput();
        logOutput.outputLog();
    }
}
